CREATE DATABASE IF NOT EXISTS bdoctans;
USE bdoctans;


CREATE TABLE IF NOT EXISTS ROL (
  ID_ROL int(11) NOT NULL AUTO_INCREMENT,
  NOMBRE varchar(100) NOT NULL,
  PRIMARY KEY (ID_ROL)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

INSERT INTO ROL (ID_ROL, NOMBRE) VALUES
	(1, 'ADMINISTRADOR'),
	(2, 'AUDITOR'),
	(3, 'AUXILIAR');

CREATE TABLE IF NOT EXISTS USUARIO (
  ID_USUARIO int(11) NOT NULL AUTO_INCREMENT,
  ID_ROL int(11) NOT NULL,
  NOMBRE varchar(100) NOT NULL,
  ACTIVO char(1) NOT NULL,
  PRIMARY KEY (ID_USUARIO),
  KEY USUARIO_FK (ID_ROL),
  CONSTRAINT USUARIO_FK FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

INSERT INTO USUARIO (ID_ROL, NOMBRE, ACTIVO) VALUES
	(1, 'Yiordi Murillo', '1');
