spring:
  datasource:
    password: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3380/bdoctans
    username: root
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8180
  error:
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: true